### ISSUE TITLE
FR: Add Entry Types as a search parameter

### ISSUE THREAD

**Issue by adrienne** [nilsenpaul/craft-easy-search#7]
I love Easy Search but i have a site where we're using Entry Types heavily and I'd love to be able to search based on those. Can that be added?

**Comment by nilsenpaul** [comment]
Hi Adrienne,

Seems like a good addition! We'll add this ASAP.

**Comment by nilsenpaul** [comment]
Adrienne, we were a bit too confident :)

Because Easy Search only 'builds' your search query, we depend on the searchable attributes that Craft itself defines. Simply searching for `entryType:article` wouldn't work (because according to https://craftcms.com/docs/3.x/searching.html#searching-for-specific-element-attributes, entryType is not a search attribute).

If you can, however, give us a search query that you know works, we can implement it.

**Comment by adrienne** [comment]
@nilsenpaul - apparently not possible yet, it turns out, so i guess it's a thing to revisit after V4 comes out! (In the meantime, i am indeed going to use a Preparse field.)

![image](https://user-images.githubusercontent.com/89705/115432482-4267fe80-a1bb-11eb-9abe-1e7a9baac9d3.png)

**Comment by adrienne** [comment]
@nilsenpaul - having done that, though, I've just run into an issue: Easy Search doesn't pick up my preparse fields as being searchable! So that part is still a FR

**Comment by nilsenpaul** [comment]
Adrienne, does a Preparse field have a 'Use this field's values as search keywords' setting for this, as mentioned [here](https://craftcms.com/docs/3.x/searching.html#configuring-custom-fields-for-search)? And if so, is it checked?

**Comment by adrienne** [comment]
@nilsenpaul - argh. Yes, it does, and no, it wasn't. I could've sworn i had checked it but apparently i fumble-fingered it. Sorry! User error!

**Comment by nilsenpaul** [comment]
No problem! Does it work now?

**Comment by adrienne** [comment]
@nilsenpaul it does! Sorry about that!
